---
- name: 'configuration | nmstate | install package'
  ansible.builtin.package:
    name: 'nmstate'
    state: present

- name: 'configuration | nmstate | enable service'
  ansible.builtin.service:
    name: 'nmstate.service'
    state: started
    enabled: true

- name: 'configuration | nmstate | apply configuration template'
  ansible.builtin.template:
    src: 'templates/network-config.j2'
    dest:  "{{ nmstate_config_path }}/network-config.yml"
    owner: root
    group: root
    mode: '0644'
  register: nmstate_configuration

- name: 'configuration | nmstate | apply network configuration'
  ansible.builtin.command: nmstatectl service
  when: nmstate_configuration.changed